import type { DJEvent } from '../types'

export const BUILT_IN_TEMPLATES: DJEvent[] = [
  {
    id: '__template_volleyball__',
    name: 'Volleyball',
    sport: 'Volleyball',
    occasionButtons: [
      {
        id: 'tplv-btn-1',
        label: 'ACE',
        colorHex: '#7700BB',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:3CIOopLwvyMvXk97ZEksKO', name: 'ACE' },
        startOffset: 38,
      },
      {
        id: 'tplv-btn-2',
        label: 'BOOM',
        colorHex: '#CC0000',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:1DL4gAmNtVmkJGItnChhuQ', name: 'BOOM' },
        startOffset: 0,
      },
      {
        id: 'tplv-btn-3',
        label: 'BLOCK',
        colorHex: '#0044CC',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:0o8mWfSTVG71hmWHduw7Oh', name: 'BLOCK' },
        startOffset: 0,
      },
      {
        id: 'tplv-btn-4',
        label: 'DIG',
        colorHex: '#CC5500',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:5A1Ys6d1aubTf4cBEpZ6pH', name: 'DIG' },
        startOffset: 120,
      },
      {
        id: 'tplv-btn-5',
        label: 'WAIT',
        colorHex: '#007A00',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:1FL7eUG80aeUeyMO2N4btN', name: 'WAIT' },
        startOffset: 0,
      },
      {
        id: 'tplv-btn-6',
        label: 'WHOOMP',
        colorHex: '#C71585',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:3oWXoSkjdbTlQlteizN7Hb', name: 'WHOOMP' },
        startOffset: 33,
      },
      {
        id: 'tplv-btn-7',
        label: 'BLOCK2',
        colorHex: '#885500',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:52AZYRiG39rVHn153LxNiq', name: 'BLOCK2' },
        startOffset: 2,
      },
      {
        id: 'tplv-btn-8',
        label: 'WIN',
        colorHex: '#FF69B4',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:1lCRw5FEZ1gPDNPzy1K4zW', name: 'WIN' },
        startOffset: 30,
      },
    ],
    songs: [
      {
        id: 'tplv-song-1',
        title: 'Game Time (feat. Sage the Gemini) – Flo Rida, Sage The Gemini',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:2gZy1KFFKUgw3IbRNhZEz3', name: 'Game Time' },
        startOffset: 0,
        order: 0,
        playCount: 0,
      },
      {
        id: 'tplv-song-2',
        title: "Let's Do This – Outskrts",
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:6bpAqxdQ2BocMFzRnVZGFH', name: "Let's Do This" },
        startOffset: 2,
        order: 1,
        playCount: 0,
      },
      {
        id: 'tplv-song-3',
        title: 'HandClap – Fitz and The Tantrums',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:0y3fi7fknIXOxnkbUgzT3n', name: 'HandClap' },
        startOffset: 30,
        order: 2,
        playCount: 0,
      },
      {
        id: 'tplv-song-4',
        title: 'Let Me Think About It Again – Showtek, Ida Corr',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:4J4Fk7x2y8jQBxm332n0oY', name: 'Let Me Think About It Again' },
        startOffset: 30,
        order: 3,
        playCount: 0,
      },
      {
        id: 'tplv-song-5',
        title: 'Vienna (Like a V V V V) - DJ Stari & DJ Tobi Rudig Remix – The Beachballs, DJ Stari, DJ Tobi Rudig',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:3IIck8QSteOTiwwUftWVc4', name: 'Vienna (Like a V V V V)' },
        startOffset: 0,
        order: 4,
        playCount: 0,
      },
      {
        id: 'tplv-song-6',
        title: 'Titi Me Pregunto - Bad Bunny',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:1IHWl5LamUGEuP4ozKQSXZ', name: 'Titi Me Pregunto' },
        startOffset: 30,
        order: 5,
        playCount: 0,
      },
    ],
  },
  {
    id: '__template_beachvolley__',
    name: 'Beachvolley',
    sport: 'Beachvolleyball',
    occasionButtons: [
      {
        id: 'tpl-btn-1',
        label: 'ACE',
        colorHex: '#7700BB',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:3CIOopLwvyMvXk97ZEksKO', name: 'ACE' },
        startOffset: 38,
      },
      {
        id: 'tpl-btn-2',
        label: 'BOOM',
        colorHex: '#CC0000',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:1DL4gAmNtVmkJGItnChhuQ', name: 'BOOM' },
        startOffset: 0,
      },
      {
        id: 'tpl-btn-3',
        label: 'BLOCK',
        colorHex: '#0044CC',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:0o8mWfSTVG71hmWHduw7Oh', name: 'BLOCK' },
        startOffset: 0,
      },
      {
        id: 'tpl-btn-4',
        label: 'DIG',
        colorHex: '#CC5500',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:5A1Ys6d1aubTf4cBEpZ6pH', name: 'DIG' },
        startOffset: 120,
      },
      {
        id: 'tpl-btn-5',
        label: 'WAIT',
        colorHex: '#007A00',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:1FL7eUG80aeUeyMO2N4btN', name: 'WAIT' },
        startOffset: 0,
      },
      {
        id: 'tpl-btn-6',
        label: 'WHOOMP',
        colorHex: '#C71585',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:3oWXoSkjdbTlQlteizN7Hb', name: 'WHOOMP' },
        startOffset: 33,
      },
      {
        id: 'tpl-btn-7',
        label: 'BLOCK2',
        colorHex: '#885500',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:52AZYRiG39rVHn153LxNiq', name: 'BLOCK2' },
        startOffset: 2,
      },
      {
        id: 'tpl-btn-8',
        label: 'WIN',
        colorHex: '#FF69B4',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:1lCRw5FEZ1gPDNPzy1K4zW', name: 'WIN' },
        startOffset: 30,
      },
    ],
    songs: [
      {
        id: 'tpl-song-1',
        title: 'Game Time (feat. Sage the Gemini) – Flo Rida, Sage The Gemini',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:2gZy1KFFKUgw3IbRNhZEz3', name: 'Game Time' },
        startOffset: 0,
        order: 0,
        playCount: 0,
      },
      {
        id: 'tpl-song-2',
        title: "Let's Do This – Outskrts",
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:6bpAqxdQ2BocMFzRnVZGFH', name: "Let's Do This" },
        startOffset: 2,
        order: 1,
        playCount: 0,
      },
      {
        id: 'tpl-song-3',
        title: 'HandClap – Fitz and The Tantrums',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:0y3fi7fknIXOxnkbUgzT3n', name: 'HandClap' },
        startOffset: 30,
        order: 2,
        playCount: 0,
      },
      {
        id: 'tpl-song-4',
        title: 'Let Me Think About It Again – Showtek, Ida Corr',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:4J4Fk7x2y8jQBxm332n0oY', name: 'Let Me Think About It Again' },
        startOffset: 30,
        order: 3,
        playCount: 0,
      },
      {
        id: 'tpl-song-5',
        title: 'Vienna (Like a V V V V) - DJ Stari & DJ Tobi Rudig Remix – The Beachballs, DJ Stari, DJ Tobi Rudig',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:3IIck8QSteOTiwwUftWVc4', name: 'Vienna (Like a V V V V)' },
        startOffset: 0,
        order: 4,
        playCount: 0,
      },
      {
        id: 'tpl-song-6',
        title: 'Titi Me Pregunto - Bad Bunny',
        audioSource: { type: 'spotifyTrack', uri: 'spotify:track:1IHWl5LamUGEuP4ozKQSXZ', name: 'Titi Me Pregunto' },
        startOffset: 30,
        order: 5,
        playCount: 0,
      },
    ],
  },
]
